### ISSUE TITLE
 Light-Locker-Settings not saved after reboot and logout

### ISSUE THREAD

**Issue by killajoe** [lots0logs/light-locker-settings#2]
Investigation: 
https://forum.antergos.com/topic/6467/light-locker-settings-not-saved-after-reboot-and-logout

 Light-Locker-Settings not saved after reboot and logout

Happens in Gnome-Shell to me, but also i3-wm have the issue.

**Comment by killajoe** [comment]
I can provide any testing and logs if someone tells me ;)

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/6568/monitor-doesn-t-suspend/8

Will there be some updating to this package?

**Comment by slacka** [comment]
A workaround is found here: https://antergos.com/wiki/desktops/gnome/working-solution-to-use-lightdm-and-lightlocker-under-gnome/

Could this be made the default settings for Antergos-Gnome?

**Comment by killajoe** [comment]
HAR HAR... i was writing the wiki

**Comment by s3idani** [comment]
honestly, i hate light-locker !

**Comment by slacka** [comment]
@killajoe 
Why was this closed? Has this been fixed upstream? If so, should we re-enable gsd-power plugin?
